### ISSUE TITLE
Branding, Back-end Theme Sidebar Issue

### ISSUE THREAD

**Issue by hiltonmw** [muk-it/muk_base#23] opened 2019-09-19 17:56 UTC
Hi there,

I think your back-end branding module is having some issues on my site (although, I wonder if it's from a different module.  Anyway, no matter what I set my sidebar items setting, it is only showing small icons.  Unfortunately, since my users are new, they dont' know what the modules/apps are based on icons, so I'd like to have it back to the original format of Icon + Text.

Or, if on hover-over it could display the app name, that might work too.  But ideally, getting it back closer to a default state would be great for me.  I tried setting this setting to "nothing" (blank) - but still no change - even after rebooting the server, and/or trying from a different PC.

attached is a screenshot.

Thanks in advance.
![help_image](https://user-images.githubusercontent.com/19822594/65268503-4adeeb80-dae5-11e9-9b47-e5687f574c44.png)

**Comment by keshrath** [comment] 2019-09-20 06:51
Is the sidebar set to Large in your preferences and is the screen size big enough to display the full sidebar?

**Comment by keshrath** [comment] 2019-09-20 06:52
For the future please create tickets in the right project. In this case it would be https://github.com/muk-it/muk_web

**Comment by hiltonmw** [comment] 2019-09-20 10:00
Yes. I’ve tried large.  Screen resolution should be large enough. Viewing on a 27” LCD with a resolution greater than 1200x1800.

**Comment by keshrath** [comment] 2019-09-20 10:02
![image](https://user-images.githubusercontent.com/4851083/65318771-90132400-db9e-11e9-8a95-36e75d6f7a6a.png)

**Comment by keshrath** [comment] 2019-09-20 10:04
It works on our demo server: https://demo12.mukit.at

Since I can't reproduce the bug on our demo, I will close the issue. If you have more information and it's actually a bug, I'll be happy to open the ticket again.

**Closed as completed by keshrath** 2019-09-20 10:04 UTC
Labels: Needs Information, 12.0

**Comment by hiltonmw** [comment] 2019-09-20 10:58
Are there any other ways I can attempt to troubleshoot this?

**Comment by keshrath** [comment] 2019-09-20 18:20
Make sure the modules are up to date and check the console (browser) and log (server) if you see any error messages.

**Comment by awgrass** [comment] 2022-06-04 08:36
Having exactly the same problem. I am running on Odoo version 14.0 docker. 
No errors in log console.
